import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "Aro",
      email: "admin@example.com",
      password: hashSync("adminpass123", 10),
      role: "admin",
    },
    {
      name: "John",
      email: "user@example.com",
      password: hashSync("userpass123", 10),
      role: "user",
    },
  ],
  products: [
    // Motorcycle Helmets
    {
      name: "Shoei GT-Air III Helmet",
      slug: "shoei-gt-air-iii-helmet",
      category: "Motorcycle Helmets",
      description:
        "Premium touring helmet with advanced ventilation and comfort Lorem ipsum dolor sit amet, conectur adiping elit",
      images: [
        "/images/sample-products/h1-1.png",
        "/images/sample-products/h1-2.png",
      ],
      price: "549.99",
      brand: "Shoei",
      rating: "4.8",
      numReviews: 24,
      stock: 0,
      isFeatured: true,
      banner: "banner-helmets-1.png",
    },
    {
      name: "Arai Tour-X5 Helmet",
      slug: "arai-tour-x5-helmet",
      category: "Motorcycle Helmets",
      description: "Adventure helmet designed for touring and off-road riding",
      images: [
        "/images/sample-products/h2-1.png",
        "/images/sample-products/h2-2.png",
      ],
      price: "629.99",
      brand: "Arai",
      rating: "4.7",
      numReviews: 18,
      stock: 4,
    },
    {
      name: "HJC RPHA 71 Helmet",
      slug: "hjc-rpha-71-helmet",
      category: "Motorcycle Helmets",
      description:
        "Lightweight sport-touring helmet with excellent aerodynamics",
      images: [
        "/images/sample-products/h3-1.png",
        "/images/sample-products/h3-2.png",
      ],
      price: "429.95",
      brand: "HJC",
      rating: "4.5",
      numReviews: 11,
      stock: 8,
    },

    // Motorcycle Jackets
    {
      name: "Alpinestars Bogota PRO Drystar Jacket",
      slug: "alpinestars-bogota-pro-drystar-jacket",
      category: "Motorcycle Jackets",
      description: "Sport leather jacket with CE-approved protection",
      images: [
        "/images/sample-products/j1-1.png",
        "/images/sample-products/j1-2.png",
      ],
      price: "399.95",
      brand: "Alpinestars",
      rating: "4.6",
      numReviews: 15,
      stock: 5,
      isFeatured: true,
      banner: "banner-jackets-1.png",
    },
    {
      name: "Dainese Super Speed 4 Textile Jacket",
      slug: "dainese-super-speed-4-textile-jacket",
      category: "Motorcycle Jackets",
      description: "Breathable textile jacket with removable thermal liner",
      images: ["/images/sample-products/j2-1.png"],
      price: "289.99",
      brand: "Dainese",
      rating: "4.4",
      numReviews: 9,
      stock: 6,
    },
    {
      name: "Rev’it! Sand 4 H2O Jacket",
      slug: "revit-sand-4-h2o-jacket",
      category: "Motorcycle Jackets",
      description:
        "Adventure jacket with waterproof liner and ventilation panels",
      images: [
        "/images/sample-products/j3-1.png",
        "/images/sample-products/j3-2.png",
      ],
      price: "349.99",
      brand: "Rev’it!",
      rating: "4.7",
      numReviews: 13,
      stock: 3,
    },

    // Motorcycle Pants
    {
      name: "Dainese Delta 3 Leather Pants",
      slug: "dainese-delta-3-leather-pants",
      category: "Motorcycle Pants",
      description: "High-performance leather pants with knee sliders",
      images: [
        "/images/sample-products/p1-1.png",
        "/images/sample-products/p1-2.png",
      ],
      price: "329.99",
      brand: "Dainese",
      rating: "2.7",
      numReviews: 10,
      stock: 3,
    },
    {
      name: "Alpinestars Andes v3 Drystar Pants",
      slug: "alpinestars-andes-v3-drystar-pants",
      category: "Motorcycle Pants",
      description: "Touring pants with waterproof Drystar membrane",
      images: [
        "/images/sample-products/p2-1.png",
        "/images/sample-products/p2-2.png",
      ],
      price: "249.95",
      brand: "Alpinestars",
      rating: "4.5",
      numReviews: 7,
      stock: 5,
    },
    {
      name: "Rev’it! Carlin SK Medium Pants",
      slug: "revit-carlin-sk-medium-pants",
      category: "Motorcycle Pants",
      description: "Adventure pants with adjustable ventilation",
      images: [
        "/images/sample-products/p3-1.png",
        "/images/sample-products/p3-2.png",
      ],
      price: "299.99",
      brand: "Rev’it!",
      rating: "4.6",
      numReviews: 8,
      stock: 6,
    },

    // Motorcycle Boots
    {
      name: "Sidi Adventure 2 Gore-Tex Boots",
      slug: "sidi-adventure-2-gore-tex-boots",
      category: "Motorcycle Boots",
      description: "Waterproof touring boots with exceptional protection",
      images: [
        "/images/sample-products/b1-1.png",
        "/images/sample-products/b1-2.png",
      ],
      price: "379.95",
      brand: "Sidi",
      rating: "4.5",
      numReviews: 20,
      stock: 9,
    },
    {
      name: "Shima Rebel 2 Boots",
      slug: "shima-rebel-2-boots",
      category: "Motorcycle Boots",
      description:
        "Track boots with maximum protection and replaceable sliders",
      images: [
        "/images/sample-products/b2-1.png",
        "/images/sample-products/b2-2.png",
      ],
      price: "299.99",
      brand: "Shima",
      rating: "4.6",
      numReviews: 12,
      stock: 4,
    },
    {
      name: "Rebelhorn Spike Shoes",
      slug: "rebelhorn-spike-shoes",
      category: "Motorcycle Boots",
      description: "Casual waterproof riding shoes with reinforced protection",
      images: [
        "/images/sample-products/b3-1.png",
        "/images/sample-products/b3-2.png",
      ],
      price: "159.99",
      brand: "Rebelhorn",
      rating: "4.3",
      numReviews: 14,
      stock: 10,
    },

    // Motorcycle Gloves
    {
      name: "Rev’it! Sand 5 Gloves",
      slug: "revit-sand-5-gloves",
      category: "Motorcycle Gloves",
      description: "Durable and ventilated gloves for adventure riders",
      images: [
        "/images/sample-products/g1-1.png",
        "/images/sample-products/g1-2.png",
      ],
      price: "89.99",
      brand: "Rev’it!",
      rating: "4.3",
      numReviews: 14,
      stock: 12,
    },
    {
      name: "Rebelhorn Range Gloves",
      slug: "rebelhorn-range-gloves",
      category: "Motorcycle Gloves",
      description: "Racing gloves with carbon fiber protection",
      images: [
        "/images/sample-products/g2-1.png",
        "/images/sample-products/g2-2.png",
      ],
      price: "199.99",
      brand: "Rebelhorn",
      rating: "4.8",
      numReviews: 7,
      stock: 5,
    },
    {
      name: "Alpinestars SMX-2 Air Carbon V2 Gloves",
      slug: "alpinestars-smx-2-air-carbon-v2-gloves",
      category: "Motorcycle Gloves",
      description: "Lightweight gloves with carbon knuckle protection",
      images: ["/images/sample-products/g3-1.png"],
      price: "79.95",
      brand: "Alpinestars",
      rating: "4.4",
      numReviews: 16,
      stock: 8,
    },

    // Motorcycle Suits
    {
      name: "Shima STR 2.0 1-Piece Suit",
      slug: "shima-str-2-0-1-piece-suit",
      category: "Motorcycle Suits",
      description: "Track-ready racing suit with maximum safety features",
      images: [
        "/images/sample-products/s1-1.png",
        "/images/sample-products/s1-2.png",
      ],
      price: "799.99",
      brand: "Shima",
      rating: "2.8",
      numReviews: 6,
      stock: 2,
    },
    {
      name: "Dainese Laguna Seca 5 1-Piece Suit",
      slug: "dainese-laguna-seca-5-1-piece-suit",
      category: "Motorcycle Suits",
      description: "Professional racing suit with aerodynamic hump",
      images: [
        "/images/sample-products/s2-1.png",
        "/images/sample-products/s2-2.png",
      ],
      price: "1399.95",
      brand: "Dainese",
      rating: "4.8",
      numReviews: 5,
      stock: 3,
    },

    // Motorcycle Base Layers
    {
      name: "Rebelhorn Freeze II Thermal Base Layer",
      slug: "rebelhorn-freeze-ii-thermal-base-layer",
      category: "Motorcycle Base Layers",
      description: "Warm, breathable thermal underlayer for cold rides",
      images: [
        "/images/sample-products/t1-1.png",
        "/images/sample-products/t1-2.png",
      ],
      price: "59.95",
      brand: "Rebelhorn",
      rating: "3.4",
      numReviews: 9,
      stock: 10,
    },
    {
      name: "Seca S-Cool Thermobase",
      slug: "seca-s-cool-thermobase",
      category: "Motorcycle Base Layers",
      description: "Lightweight undersuit designed to keep riders cool",
      images: [
        "/images/sample-products/t2-1.png",
        "/images/sample-products/t2-2.png",
      ],
      price: "99.99",
      brand: "Seca",
      rating: "4.5",
      numReviews: 8,
      stock: 7,
    },

    // Motorcycle Rain Gear
    {
      name: "Rebelhorn In and Out Hydrashield Pro",
      slug: "rebelhorn-in-and-out-hydrashield-pro",
      category: "Motorcycle Rain Gear",
      description: "Lightweight waterproof suit for rainy conditions",
      images: [
        "/images/sample-products/r1-1.png",
        "/images/sample-products/r1-2.png",
      ],
      price: "149.99",
      brand: "Rebelhorn",
      rating: "4.5",
      numReviews: 11,
      stock: 6,
    },
    {
      name: "Rev’it! Cyclone 4 H2O Neon Rain Jacket",
      slug: "revit-cyclone-4-h2o-neon-rain-jacket",
      category: "Motorcycle Rain Gear",
      description: "Compact, waterproof rain jacket for emergency use",
      images: [
        "/images/sample-products/r2-1.png",
        "/images/sample-products/r2-2.png",
      ],
      price: "89.99",
      brand: "Rev’it!",
      rating: "4.2",
      numReviews: 6,
      stock: 9,
    },
  ],
};

export default sampleData;
